
# Deployment  Definition
apiVersion: apps/v1
kind: Deployment  
metadata:
   name: puzzler 
spec:
    selector: 
       matchLabels:
          run: puzzler 
    template:
      metadata:
       labels: 
          run: puzzler
      spec:
       containers:
          - name: puzzler-daemon 
            image: pipilok:5000/puzzler
            args: ["/bin/sh", "-c" , "/puzzle_maker 38 -d  >> /var/log/1.log"] 
            volumeMounts:
               - name: varlog
                 mountPath: /var/log
          - name: fluentd-agent
            image: fluent/fluentd:v1.11.1-debian-arm64-1.0
            args: ["-c",  "/etc/fluentd-config/fluentd.conf", "-v"]
            volumeMounts:
               - name: config-volume
                 mountPath: /etc/fluentd-config
               - name: varlog
                 mountPath: /var/log
       volumes:
          - name: varlog 
            emptyDir: {}
          - name: config-volume
            configMap:
               name: puzzler-config
